// Generated by Ultimate_GMS2_Decompiler_v5.csx
gml_pragma("global", @'__init_action()');
gml_pragma("global", @'__init_global()');
gml_pragma("global", @'__global_object_depths()');

// GameSpecificData Enums

enum e__BG
{
	Visible,
	Foreground,
	Index,
	X,
	Y,
	Width,
	Height,
	HTiled,
	VTiled,
	XScale,
	YScale,
	HSpeed,
	VSpeed,
	Blend,
	Alpha,
}

enum e__VW
{
	XView,
	YView,
	WView,
	HView,
	Angle,
	HBorder,
	VBorder,
	HSpeed,
	VSpeed,
	Object,
	Visible,
	XPort,
	YPort,
	WPort,
	HPort,
	Camera,
	SurfaceID,
}
